### ISSUE TITLE
httpd

### ISSUE THREAD

**Issue by Dane-Z** [mestia/cellxgene-gateway-proxy-example#1]
Hi, my lab is trying to set up a reverse proxy host of cellxgene using your guide but we're not sure how to proceed. We're using RHEL8 and much of this tutorial is tough to convert with the differing file systems. Do you happen to know of a resource for setting this up via httpd in CentOS or RHEL8 distros of linux?

**Comment by mestia** [comment]
Hey, in fact the configuration is pretty simple. What you see in this repository is just a bunch of scripts to optimize the setup of the new groups. If you manage to setup one working instance, it should be fairly easy to adjust the scripts.
I will be glad to help if you provide more details about what exactly doesn't work. You basically need working httpd+mod_ssl and mod_auth_form ( comes from mod_form yum package ) first.

**Comment by Dane-Z** [comment]
Okay that may be the issue. We're having trouble setting up a working instance through the apache server at the moment for even one group. It looks like we have mod_ssl installed but just installed and enabled mod_auth_form (although it was from the mod_session package in RHEL8). Now that mod_auth_form is working, I'll try re-running the scripts.

**Comment by Dane-Z** [comment]
Hi again, downloading the required packages fixed the issues I was facing but I'm facing an issue with cellxgene-gateway that I'm not sure how to fix. If you're willing to help, I'm receiving this when running cellxgene-gateway: "Running on http://0.0.0.0:5005/". This seems to be a default IP location but I'm not sure where cellxgene is pulling this from so I'm unable to change it.

**Comment by mestia** [comment]
Hi, `0.0.0.0:5005` means that the service is listening on all interfaces, so for example in case you run it on your machine, typing in a browser http://localhost:5005 or http://<current_ip_address>:5005 should do the same. In case it is a remote machine, you'll have to use it's name/ip address.

**Comment by Dane-Z** [comment]
So if I'm trying to access the example pbmc3k.h5ad cellxgene data, I'd need to use the ip address for that when running cellxgene-gateway?

Also, I have this for my cellxgene_<group>.service file, which I assume starts cellxgene-gateway and exports the following variables? However, when I start cellxgene-gateway from the command line it doesn't set the correct port, so I'm not sure if this is correct. 

[Unit]
Description=groupx
After=systemd-user-sessions.service

[Service]
User=user
WorkingDirectory=/home/user
Environment=CELLXGENE_LOCATION=/home/user/local/bin/cellxgene
Environment=CELLXGENE_DATA=/home/user/cellxgene_data
Environment=GATEWAY_PORT=5483
Environment=GATEWAY_ENABLE_ANNOTATIONS=1
ExecStart=/home/user/local/bin/cellxgene-gateway
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by mestia** [comment]
Check if the port is already in use, in any case this is the issue with cellxgene-gateway, not the proxy as far as I understand. Proxy suppose to use cellxgene-gateway instance as a backend and connect over http.

**Comment by Dane-Z** [comment]
Thanks for the help! We were able to get an instance of cellxgene-gateway running. We are now rethinking exactly what we want to achieve. We want to be able to call an instance of cellxgene on our remote server and be able to share a web url link to others on the remote server that will allow them to access that instance. We think we need a reverse proxy to do this but are not sure. This is what this tutorial is meant for, correct?

**Comment by Dane-Z** [comment]
Hi again, we have one last question. Your code is great and we are able to make the service, index, and conf files for each of our groups but we've run into a problem. When we navigate to the URL after activating the the service and apache, we get to this page:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/80366234/180841806-7b3d8b55-1cad-4a5e-b6b3-422fc65a5e5a.png">

When we click on the group links we receive an error:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/80366234/180841912-d72cbd0a-b279-4f29-a659-4ac79792076f.png">

We are able to get cellxgene-gateway to work normally using the service daemon, but when using apache/httpd nothing appears. We set the parameters as follows without using the apache server and were able to finally get it to run on our site with the proper port:
[Unit]
Description=cellxgene-gateway-daemon
After=systemd-user-sessions.service

[Service]
User=user
WorkingDirectory=/home/Public_Data/
Environment=CELLXGENE_LOCATION=/usr/local/bin/cellxgene
Environment=CELLXGENE_DATA=/home/Public_Data/cellxgene_data/groupx
Environment=EXTERNAL_HOST=sshserverIP:5006
Environment=EXTERNAL_PROTOCOL=http
Environment=GATEWAY_IP=sshserverIP
Environment=GATEWAY_PORT=5006
Environment=GATEWAY_ENABLE_ANNOTATIONS=1
ExecStart=/usr/local/bin/cellxgene-gateway
Restart=always

[Install]
WantedBy=multi-user.target

We want to use apache to keep different groups' data private to each group, but we're not sure where each link from the group name is supposed to go next and if we have set the paremeters for the IP incorrectly. We first want to get the links working before we worry about the login page so we have commented out the authorization LDAP information for now. Once we click on a group name is it supposed to load the clogin index.html then navigate to cellxgene-gateway?

**Comment by mestia** [comment]
First sorry for the long delay.
The index.html file has sections matching the apache2 config <Locations> and RewriteRule sections
Once clicked, the apache2 reverse proxy config will take care of processing and proxying the request to the corresponding service.

For example `<li><a href="/groupX/">groupX</a></li>` from the template index.html suppose to be handled by [groupx.conf](https://github.com/mestia/cellxgene-gateway-proxy-example/tree/main/etc/apache2/sites-available/cellxgene) and the corresponding service suppose to listen on port `5006`.
